import { FieldConfig } from "@/shared/types/form/form-builder";

export const modelFieldConfig: FieldConfig[] = [
  {
    name: "height_cm",
    label: "قد",
    type: "text",
    placeholder: "175",
    numericOnly: true,
    required: true,
    variant: "secondary",
  },
  {
    name: "weight_kg",
    label: "وزن",
    type: "text",
    placeholder: "70",
    numericOnly: true,
    required: true,
    variant: "secondary",
  },
  {
    name: "skin_color",
    label: "رنگ پوست",
    type: "text",
    placeholder: "مثال: روشن",
    required: true,
    variant: "secondary",
  },
  {
    name: "eye_color",
    label: "رنگ چشم",
    type: "text",
    placeholder: "مثال: قهوه‌ای",
    required: true,
    variant: "secondary",
  },
  {
    name: "hair_color",
    label: "رنگ مو",
    type: "text",
    placeholder: "مثال: مشکی",
    required: true,
    variant: "secondary",
  },
];

export const employerFieldConfig: FieldConfig[] = [
  {
    name: "company_type",
    label: "نوع فعالیت",
    type: "select",
    placeholder: "یک آیتم انتخاب کنید",
    options: [
      { label: "شخص حقیقی", value: "individual" },
      { label: "شرکت", value: "company" },
      { label: "آژانس", value: "agency" },
    ],
    required: true,
    variant: "secondary",
  },
  {
    name: "company_name",
    label: "نام شرکت / برند",
    type: "text",
    placeholder: "مثال: آژانس مد پارسه",
    required: true,
    variant: "secondary",
  },
  {
    name: "email",
    label: "ایمیل",
    type: "email",
    placeholder: "example@email.com",
    required: true,
    variant: "secondary",
  },
  {
    name: "website",
    label: "وبسایت",
    type: "text",
    placeholder: "https://example.com",
    required: false,
    variant: "secondary",
  },
  {
    name: "instagram",
    label: "اینستاگرام",
    type: "text",
    placeholder: "lumine@",
    required: false,
    variant: "secondary",
  },
  {
    name: "city",
    label: "شهر",
    type: "text",
    placeholder: "تهران",
    required: true,
    variant: "secondary",
  },
  {
    name: "address",
    label: "آدرس",
    type: "textarea",
    placeholder: "آدرس کامل را وارد کنید",
    required: true,
    variant: "secondary",
  },
  {
    name: "description",
    label: "توضیحات",
    type: "textarea",
    placeholder: "درباره کسب‌وکار خود بنویسید...",
    required: false,
    variant: "secondary",
  },
];

export const instructorFieldConfig: FieldConfig[] = [
  {
    name: "years_of_experience",
    label: "سال‌های تجربه",
    type: "text",
    placeholder: "مثال: 5",
    numericOnly: true,
    required: true,
    variant: "secondary",
  },
  {
    name: "certifications",
    label: "آخرین مدرک تحصیلی",
    placeholder: "انتخاب کنید",
    type: "select",
    options: [
      { label: "دیپلم", value: "diploma" },
      { label: "کارشناسی", value: "bachelor" },
      { label: "کارشناسی ارشد", value: "master" },
      { label: "دکترا", value: "PhD" },
    ],
    required: true,
    variant: "secondary",
  },
  {
    name: "workshop_types",
    label: "نوع تدریس",
    placeholder: "انتخاب کنید",
    type: "select",
    options: [
      { label: "آنلاین", value: "online" },
      { label: "حضوری", value: "in_person" },
      { label: "خصوصی", value: "private" },
    ],
    required: true,
    variant: "secondary",
  },
  {
    name: "email",
    label: "ایمیل",
    type: "email",
    placeholder: "example@email.com",
    required: true,
    variant: "secondary",
  },
  {
    name: "website",
    label: "وبسایت",
    type: "text",
    placeholder: "https://example.com",
    required: false,
    variant: "secondary",
  },
  {
    name: "instagram",
    label: "اینستاگرام",
    type: "text",
    placeholder: "lumine@",
    required: false,
    variant: "secondary",
  },
  {
    name: "city",
    label: "شهر",
    type: "text",
    placeholder: "تهران",
    required: true,
    variant: "secondary",
  },
  {
    name: "description",
    label: "توضیحات",
    type: "textarea",
    placeholder: "درباره تجربیات تدریس خود بنویسید...",
    required: false,
    variant: "secondary",
  },
];

export const roleFieldConfigMap: Record<string, FieldConfig[]> = {
  model: modelFieldConfig,
  employer: employerFieldConfig,
  instructor: instructorFieldConfig,
};

export const roleTitleMap: Record<string, string> = {
  model: "اطلاعات تکنیکال",
  employer: "اطلاعات کارفرمایی",
  instructor: "اطلاعات مدرس",
};
