# Generated by Django 6.0.3 on 2026-07-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_province'),
        ('projects', '0005_projectrequest_updated_alter_projectrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'درحال بررسی'), ('approved', 'قبول شده'), ('rejected', 'رد شده')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='authentication.province'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('open', 'باز'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('closed', 'بسته شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20),
        ),
    ]
