# Generated by Django 6.0.3 on 2026-07-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_province'),
        ('projects', '0006_project_moderation_status_project_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='authentication.province'),
        ),
    ]
