# Generated by Django 6.0.3 on 2026-04-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_employerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='temp',
            new_name='text_error',
        ),
    ]
