# Generated by Django 6.0.3 on 2026-05-02 18:12

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_rename_temp_user_text_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.PositiveBigIntegerField()),
                ('certifications', models.CharField(choices=[('دیپلم', 'diploma'), ('کارشناسی', 'bachelor'), ('کارشناسی ارشد', 'master'), ('دکترا', 'PhD')], max_length=20)),
                ('workshop_types', models.CharField(choices=[('آنلاین', 'online'), ('حضوری', 'in_person'), ('خصوصی', 'private')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
