# Generated by Django 6.0.3 on 2026-05-02 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_instructorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='years_of_experience',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
