# Generated by Django 6.0.3 on 2026-05-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_instructorprofile_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='certifications',
            field=models.CharField(choices=[('diploma', 'دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('PhD', 'دکترا')], max_length=20),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='workshop_types',
            field=models.CharField(choices=[('online', 'آنلاین'), ('in_person', 'حضوری'), ('private', 'خصوصی')], max_length=20),
        ),
    ]
