# Generated by Django 6.0.3 on 2026-05-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_instructorprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, choices=[('IR', 'ایرانی'), ('FR', 'غیرایرانی')], max_length=10, null=True),
        ),
    ]
