# Generated by Django 6.0.3 on 2026-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_user_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='persion_name',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('model', 'مدل'), ('instructor', 'مدرس'), ('employer', 'کارفرما')], max_length=250, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type'], name='authenticat_type_d0af4b_idx'),
        ),
    ]
