# Generated by Django 6.0.3 on 2026-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_rename_description_category_persion_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=55, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
